# Importing libraries

In [1]:
import numpy as np
import keras
import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow as tf
from sklearn.tree import DecisionTreeClassifier
import random
from sklearn.metrics import accuracy_score

# Importing MNIST Dataset

In [2]:
(x_train, y_train), (x_test, y_test)=tf.keras.datasets.mnist.load_data(path="mnist.npz")


In [3]:
data_x=np.concatenate((x_train,x_test))
data_y=np.concatenate((y_train,y_test))

In [4]:
data_x.shape

(70000, 28, 28)

In [5]:
np.unique(data_x)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

# Flattening

In [6]:
num_pixels = data_x.shape[1] * data_x.shape[2]
data_x = data_x.reshape((data_x.shape[0], num_pixels)).astype('float32')

In [7]:
np.unique(data_x)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
       121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131.,
       132., 133., 134., 135., 136., 137., 138., 139., 140., 141., 142.,
       143., 144., 145., 146., 147., 148., 149., 15

# Binary vector

In [8]:
data_x=data_x/255.

In [9]:
data_x=np.where(data_x>0.5,1,0)

# Spliting into train, test and validation

In [10]:
X_train, X_test_val, y_train, y_test_val = train_test_split(data_x, data_y, test_size=0.4, random_state=42)

In [11]:
X_val, X_test, y_val, y_test = train_test_split(X_test_val, y_test_val, test_size=0.5, random_state=42)

In [12]:
X_train.shape

(42000, 784)

In [13]:
X_val.shape

(14000, 784)

In [14]:
X_test.shape

(14000, 784)

# Building a decision tree

In [15]:
#random.seed(42)
rand=[]
for i in range(10):
    rand.append(random.randint(0,783))

In [16]:
rand

[496, 493, 161, 91, 182, 31, 411, 10, 23, 638]

In [17]:
clf = DecisionTreeClassifier(random_state=0,max_depth=5)

In [18]:
X_train[:,rand].shape

(42000, 10)

In [19]:
clf.fit(X_train[:,rand],y_train)

DecisionTreeClassifier(max_depth=5, random_state=0)

In [20]:
y_pred=clf.predict(X_val[:,rand])

In [21]:
accuracy_score(y_val, y_pred)

0.30742857142857144

# Repeating this process for 50 random subsets

In [22]:
#random.seed(42)
accuracy=[]
test_proba=[]
for j in range(50):
    rand=[]
    for i in range(10):
        rand.append(random.randint(0,783))
    clf = DecisionTreeClassifier(random_state=0,max_depth=5)
    clf.fit(X_train[:,rand],y_train)
    y_pred=clf.predict(X_val[:,rand])
    test_proba.append(clf.predict_proba(X_test[:,rand]))
    accuracy.append(accuracy_score(y_val, y_pred))

In [23]:
accuracy=np.array(accuracy)
accuracy.shape

(50,)

In [24]:
accuracy

array([0.31121429, 0.29435714, 0.377     , 0.34271429, 0.34971429,
       0.26021429, 0.32485714, 0.44092857, 0.24507143, 0.36864286,
       0.23407143, 0.277     , 0.36207143, 0.32992857, 0.32642857,
       0.30028571, 0.36292857, 0.37907143, 0.1805    , 0.16378571,
       0.28728571, 0.16      , 0.30492857, 0.28907143, 0.31357143,
       0.36007143, 0.15678571, 0.31964286, 0.22792857, 0.303     ,
       0.31985714, 0.33314286, 0.22692857, 0.23678571, 0.36107143,
       0.27607143, 0.45128571, 0.33      , 0.36421429, 0.29685714,
       0.2995    , 0.37321429, 0.23064286, 0.38721429, 0.3065    ,
       0.34957143, 0.31921429, 0.31764286, 0.30535714, 0.32492857])

# Weighted classification of the test set

In [25]:
test_proba=np.array(test_proba)

In [26]:
test_proba.shape

(50, 14000, 10)

In [27]:
accuracy.shape

(50,)

In [28]:
def weighted_sum(test_proba,W):
    s_w=np.sum(W)
    s_w_pred=np.zeros((test_proba.shape[1],test_proba.shape[2]))
    for i in range(50):
        y=W[i]*test_proba[i]
        s_w_pred=s_w_pred+y
    y_pred=s_w_pred/s_w
    return y_pred

In [29]:
y_pred=weighted_sum(test_proba,accuracy)

In [30]:
y_pred.shape

(14000, 10)

In [31]:
y_pred_2=np.argmax(y_pred,axis=1)

In [32]:
y_pred_2.shape

(14000,)

# Accuracy on test set using weighted classification

In [33]:
accuracy_score(y_test, y_pred_2)

0.7767142857142857

# Adaboast 

In [87]:
#randomly selecting 15 features
#rand=[]
#for i in range(15):
#    rand.append(random.randint(0,783))
#rand

[44, 165, 329, 91, 58, 634, 173, 169, 213, 224, 612, 513, 639, 126, 549]

In [104]:
weights=[1/X_train.shape[0]]*X_train.shape[0]

In [105]:
def I(flag):
    return 1 if flag else 0

In [106]:
models=[]
w=[]
for i in range(20):
    clf=DecisionTreeClassifier(max_depth=5)
    clf.fit(X_train,y_train,sample_weight=weights)
    #calculating weighted error
    weighted_error=sum([weights[j]*I(y_train[j]!=clf.predict(np.expand_dims(X_train[j],axis=0)))
                                      for j in range(X_train.shape[0])])/sum(weights)
     #Setting weightage  
    Alpha = 0.5*np.log((1-weighted_error)/weighted_error)
    # update weights
    weights = [weights[j]*np.exp(Alpha*I(y_train[j]!=clf.predict(np.expand_dims(X_train[j],axis=0))))for j in range(X_train.shape[0])]
    weights = [weights[j]*np.exp(-Alpha*I(y_train[j]==clf.predict(np.expand_dims(X_train[j],axis=0))))for j in range(X_train.shape[0])]
    #normalizing weights
    weights=weights/sum(weights)
    #saving weights and classifier                                                
    models.append(clf)
    w.append(Alpha)                                                

In [107]:
models

[DecisionTreeClassifier(max_depth=5),
 DecisionTreeClassifier(max_depth=5),
 DecisionTreeClassifier(max_depth=5),
 DecisionTreeClassifier(max_depth=5),
 DecisionTreeClassifier(max_depth=5),
 DecisionTreeClassifier(max_depth=5),
 DecisionTreeClassifier(max_depth=5),
 DecisionTreeClassifier(max_depth=5),
 DecisionTreeClassifier(max_depth=5),
 DecisionTreeClassifier(max_depth=5),
 DecisionTreeClassifier(max_depth=5),
 DecisionTreeClassifier(max_depth=5),
 DecisionTreeClassifier(max_depth=5),
 DecisionTreeClassifier(max_depth=5),
 DecisionTreeClassifier(max_depth=5),
 DecisionTreeClassifier(max_depth=5),
 DecisionTreeClassifier(max_depth=5),
 DecisionTreeClassifier(max_depth=5),
 DecisionTreeClassifier(max_depth=5),
 DecisionTreeClassifier(max_depth=5)]

In [108]:
w

[0.2786110053053166,
 0.12487408747233113,
 0.0732575723216936,
 0.007485140663422213,
 0.015723118984558852,
 0.07815613836905128,
 0.0456062706404066,
 0.023003938869446246,
 0.019605372284802722,
 -0.02372972136405102,
 3.241851231905352e-14,
 -1.7541523789077783e-14,
 1.1990408665951547e-14,
 1.9539925233402373e-14,
 -2.509104035652917e-14,
 -8.88178419700126e-16,
 2.975397705995331e-14,
 -5.107025913275981e-14,
 6.039613253960487e-14,
 -6.12843109593124e-14]

# Classification on the test set

In [109]:
y_pred=0
for m in range(20):
            clf,Alpha = models[m],w[m]
            y_pred += Alpha*clf.predict_proba(X_test)
y_pred=np.array(abs(y_pred))
y_pred_2=np.argmax(y_pred,axis=1)

In [110]:
y_pred_2.shape

(14000,)

In [111]:
accuracy_score(y_test, y_pred_2)

0.7172857142857143